name: CI
on:
  push:
    branches: [ 'master' ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build container
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          load: true

      - name: Test image
        run: scripts/test.sh ${{ steps.build.outputs.imageid }}

      - name: Tags
        id: metadata
        run: |
          CONTAINER=ghcr.io/guymers/unifi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "tags=${CONTAINER}:nightly" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tags=${CONTAINER}:${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: GitHub Container registry
        if: ${{ steps.metadata.outputs.tags }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        if: ${{ steps.metadata.outputs.tags }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: linux/arm64/v8,linux/amd64
          tags: ${{ steps.metadata.outputs.tags }}
