name: CI
on:
  push:
    branches: [ 'master' ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: localhost/test

      - name: Test image
        run: |
          docker run -d --rm --name unifitest localhost/test &&
          sleep 35 &&
          for i in $(seq 1 10); do [ $(docker inspect --format='{{json .State.Health.Status}}' unifitest ) == \"healthy\" ] && break ||  sleep 35; done &&
          [ $(docker inspect --format='{{json .State.Health.Status}}' unifitest ) == \"healthy\" ] &&
          docker stop unifitest

      - name: Tags
        id: metadata
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo ::set-output name=tags::guymers/unifi:nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=tags::guymers/unifi:${GITHUB_REF#refs/tags/}
          fi

      - name: GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        if: ${{ steps.metadata.outputs.tags }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
